### ISSUE TITLE
Precision loss when output to 

### ISSUE THREAD

**Issue by centurn** [grisu48/geoJson#2]
Output json loses the precision comparing to original track. The image shows original GPX track in teal color, and converted json in red.
![image](https://user-images.githubusercontent.com/4426387/104128915-40500180-537b-11eb-89e7-14ec4d650c3b.png)

The reason seems to be default ostream format. I've put 
out << setprecision(7)
before the dump code and that fixes the problem. That should mean 1m precision at worst - we certainly don't need all 10+ decimals from original gpx from Garmin, but by default the iostream sometimes produces less than 5.

BTW, thanks for the code! It may be simple, as you mention in readme, but it's the best-suited that I've found. Going to use it to pre-process tracks to minimize the download sizes for Leaflet maps: (along with removing whitespaces). XML is evil!

**Comment by grisu48** [comment]
Wow, thanks for the input! This looks like a really easy fix, gonna include this ASAP

**Comment by grisu48** [comment]
Included in https://github.com/grisu48/geoJson/pull/3. Thanks for reporting! :slightly_smiling_face:
